name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build the Project
        run: dotnet build --no-restore
      - name: Test the Code
        run: dotnet test --no-build --verbosity normal
      - name: Build and Bundle for MacOS
        run: dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=false
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/Debug/net5.0/osx-x64/publish/render
